name: Android CI
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Set up gradle
      uses: gradle/gradle-build-action@v2
    - name: Build with Gradle
      run: chmod +x ./gradlew && ./gradlew build --stacktrace -Dtrace assembleDebug assembleRelease
    - name: Upload apks
      uses: actions/upload-artifact@v3
      with:
        name: apks
        path: |
          app/build/outputs/apk/debug/app-debug.apk
          app/build/outputs/apk/release/app-release*.apk
